.TH LIBERROR_END 3 2019-04-13 liberror
.SH NAME
liberror_end \- restore the thread's error state
.SH SYNOPSIS
.nf
#include <liberror.h>

void liberror_end(const struct liberror_state *\fIstate\fP);
.fi
.PP
Link with
.IR \-lerror .
.SH DESCRIPTION
The
.BR liberror_end ()
function restores the state saved and cleared
by the
.BR liberror_start (3)
function.
.PP
Asynchronously called functions such as single
handlers shall call this function the last thing
they do before returning.
.SH RETURN VALUE
None.
.SH ERRORS
None.
.SH EXAMPLES
None.
.SH APPLICATION USAGE
None.
.SH RATIONALE
None.
.SH FUTURE DIRECTIONS
None.
.SH NOTES
None.
.SH SEE ALSO
.BR liberror (7),
.BR liberror.h (0),
.BR liberror_copy_error (3),
.BR liberror_free_error (3),
.BR liberror_get_error (3),
.BR liberror_pop_error (3),
.BR liberror_print_backtrace (3),
.BR liberror_print_error (3),
.BR liberror_reset_error (3),
.BR liberror_save_backtrace (3),
.BR liberror_set_error (3),
.BR liberror_set_error_errno (3),
.BR liberror_set_error_existing (3),
.BR liberror_start (3)
