.TH LIBERROR_FREE_ERROR 3 2019-04-13 liberror
.SH NAME
liberror_free_error \- deallocate an error
.SH SYNOPSIS
.nf
#include <liberror.h>

void liberror_free_error(struct liberror_error *\fIerror\fP);
.fi
.PP
Link with
.IR \-lerror .
.SH DESCRIPTION
The
.BR liberror_free_error ()
function deallocates
.I error
recursively. If
.I error
is
.I NULL
the function will return without doing anything.
.SH RETURN VALUE
None.
.SH ERRORS
None.
.SH EXAMPLES
None.
.SH APPLICATION USAGE
None.
.SH RATIONALE
None.
.SH FUTURE DIRECTIONS
None.
.SH NOTES
None.
.SH SEE ALSO
.BR liberror (7),
.BR liberror.h (0),
.BR liberror_copy_error (3),
.BR liberror_end (3),
.BR liberror_get_error (3),
.BR liberror_print_bactrace (3),
.BR liberror_print_error (3),
.BR liberror_reset_error (3),
.BR liberror_save_backtrace (3),
.BR liberror_set_error (3),
.BR liberror_set_error_errno (3),
.BR liberror_start (3)
