.TH LIBERROR_START 3 2019-04-13 liberror
.SH NAME
liberror_start \- save and reset the thread's error state
.SH SYNOPSIS
.nf
#include <liberror.h>

void liberror_start(struct liberror_state *\fIstate\fP);
.fi
.PP
Link with
.IR \-lerror .
.SH DESCRIPTION
The
.BR liberror_start ()
function saves the thread-local
.B liberror
variables to
.I state
as well as the value of
.IR errno ,
and resets these variables.
.PP
Asynchronously called functions such as single
handlers shall call this function the first thing
they do.
.SH RETURN VALUE
None.
.SH ERRORS
None.
.SH EXAMPLES
None.
.SH APPLICATION USAGE
None.
.SH RATIONALE
None.
.SH FUTURE DIRECTIONS
None.
.SH NOTES
None.
.SH SEE ALSO
.BR liberror (7),
.BR liberror.h (0),
.BR liberror_copy_error (3),
.BR liberror_end (3),
.BR liberror_free_error (3),
.BR liberror_get_error (3),
.BR liberror_print_backtrace (3),
.BR liberror_print_error (3),
.BR liberror_reset_error (3),
.BR liberror_save_backtrace (3),
.BR liberror_set_error (3),
.BR liberror_set_error_errno (3)
